name: Secrets Scan

on:
  workflow_dispatch:

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run GitLeaks
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --repo-path=. --report-format=csv --report-path=gitleaks-report.csv